# Generated by Django 4.0.2 on 2022-02-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_park_id', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('development', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('lot_type', models.CharField(max_length=1)),
                ('agency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CarparkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('available_lots', models.PositiveSmallIntegerField()),
                ('carpark_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_park_data_handler.carpark')),
            ],
        ),
    ]
