# Generated by Django 4.0.2 on 2022-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park_data_handler', '0002_alter_carpark_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
