# Generated by Django 4.0.2 on 2022-02-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_park_data_handler', '0003_alter_carpark_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carparkdata',
            old_name='carpark_id',
            new_name='carpark',
        ),
    ]
