# Generated by Django 4.0.2 on 2022-02-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_park_data_handler', '0004_rename_carpark_id_carparkdata_carpark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carparkdata',
            old_name='carpark',
            new_name='carpark_id',
        ),
        migrations.AlterField(
            model_name='carparkdata',
            name='carpark_id',
            field=models.ForeignKey(db_column='carpark_id', on_delete=django.db.models.deletion.DO_NOTHING, to='car_park_data_handler.carpark'),
        ),
    ]
