# Generated by Django 4.0.2 on 2022-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park_data_handler', '0005_rename_carpark_carparkdata_carpark_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparkdata',
            name='available_lots',
            field=models.SmallIntegerField(),
        ),
    ]
